### ISSUE TITLE
Fermipy unit tests are failing with "RuntimeError: Requested MET not covered by selected IRFs."

### ISSUE THREAD

**Issue by eacharles** [fermi-lat/irfs#18]
The attached .txt file is actually a python script in disguise that will trigger the error.   

[dummy_test_py.txt](https://github.com/fermi-lat/irfs/files/5120662/dummy_test_py.txt)

**Comment by eacharles** [comment]
FWIW, Adding the current MET ( i.e., 620012141) to the value() call fixes the problem.   But shouldn't all of our IRFs be valid for all times.

**Comment by eacharles** [comment]
However, note that there are still failures, e.g., : 
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
fermipy/gtanalysis.py:1071: in setup
    self._create_likelihood()
fermipy/gtanalysis.py:1096: in _create_likelihood
    c._create_binned_analysis(srcmdl)
fermipy/gtanalysis.py:5373: in _create_binned_analysis
    self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
../../../../miniconda2/envs/fermi-1.3.6-dev/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py:71: in __init__
    self._createObservation(srcMaps, expCube, self.irfs)
../../../../miniconda2/envs/fermi-1.3.6-dev/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py:107: in _createObservation
    self.observation)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pyLikelihood.MeanPsf;  >
args = (<pyIrfLoader.SkyDir; proxy of <Swig Object of type 'astro::SkyDir *' at 0x7fbbc908ec60> >, (500.0, 889.1396875, 1581....1.397, ...), <pyLikelihood.Observation; proxy of <Swig Object of type 'Likelihood::Observation *' at 0x7fbbc908e120> >)

    def __init__(self, *args):
        r"""
        __init__(MeanPsf self, double ra, double dec, DoubleVector energies, Observation observation) -> MeanPsf
        __init__(MeanPsf self, SkyDir srcDir, DoubleVector energies, Observation observation) -> MeanPsf
        """
>       _pyLikelihood.MeanPsf_swiginit(self, _pyLikelihood.new_MeanPsf(*args))
E       RuntimeError: Requested MET not covered by selected IRFs.
 
```

**Comment by eacharles** [comment]
Second piece of information, this works fine with P8R3_SOURCE_V3 but fails with P8R3_SOURCE_V2.   Perhaps you changed the validity times when you ingested V3?

**Comment by Areustle** [comment]
@jasercion is now on it, but I suspect this is related to Issue #14

**Comment by jasercion** [comment]
This is my suspicion as well, testing that out presently.  I'll also check the ranges in the updated `caldb.indx` to make sure that the validity times are still intact.

**Comment by jasercion** [comment]
Ok, I've ruled out that Issue #14 is specifically causing the problem.  Moving on to verifying the MET validity boundaries.

**Comment by jasercion** [comment]
It is in fact a boundary issue in the `caldb.indx`.  I'll get that fixed and have a patch merged hopefully by tomorrow.

**Comment by jasercion** [comment]
@eacharles This should be fixed with an update I added on the IRF-18 branch.  Can you please verify if the tools in the following python 3 build are behaving as expected?

`conda install -c conda-forge -c fermi -c fermi/label/dev fermitools=1.9.14`

**Comment by jasercion** [comment]
If everything looks good let me know and I'll merge the changes to `master`
