### ISSUE TITLE
understanding evclass=128

### ISSUE THREAD

**Issue by nkelhos** [fermi-lat/irfs#21]
I'm trying to do an analysis with P8R3_SOURCE file `lat_photon_weekly_w333_p305_v001.fits`, but I'm having trouble understanding how `gtselect evclass=128` is applied to the `EVENT_CLASS` column in that fits file.

I've used `gtselect evclass=128` with the above photon file to produce `evclass128.fits`.  I've compared the two fits files to get a list of events that pass the 128 cut, and events that fail the 128 cut.  When I compare the `EVENT_CLASS` of the pass and fail groups (the binary strings below), some event classes are in both pass and fail groups, when I would expect them to be completely exclusive.

Here's a list of various event's EVENT_CLASS, some events that pass, and others that fail the evclass=128 cut.
```
EVENT_CLASS                      evclass=128 cut
00000000000000011000100111111111 pass
00000000000000011000111111111111 pass
00000001000000000000101111111111 pass
00000001000000001000000111111111 pass
00000001000000001000100111111111 pass
00000001000000001000101111111111 pass
00000001000000001000111111111111 pass
00000001000000011000000111111111 pass
00000001000000011000001111111111 pass
00000001000000011000011111111111 pass
00000001000000011000100111111111 pass
00000001000000011000101111111111 pass
00000001000000011000111111111111 pass
00000001000000000000100111111111 fail
00000001000000000000101111111111 fail
00000001000000001000100111111111 fail
00000001000000011000000111111111 fail
00000001000000011000100111111111 fail
00000001000000011000101111111111 fail
00000001000000011000111111111111 fail
```

From that list, these EVENT_CLASSes are in both pass and fail groups:
```
00000001000000000000101111111111
00000001000000001000100111111111
00000001000000011000000111111111
00000001000000011000100111111111
00000001000000011000101111111111
00000001000000011000111111111111
```
I think this means `evclass=128` is more complicated than a simple bitmask of EVENT_CLASS, but I'm not sure how.

If I wanted to filter the events manually, is there more I need to understand about how the `evclass=128` cut is applied?

**Comment by nmirabal** [comment]
These two links can clarify the event selection
https://raw.githubusercontent.com/fermi-lat/fermitools-fhelp/master/gtselect.txt
https://fermi.gsfc.nasa.gov/ssc/data/analysis/documentation/Cicerone/Cicerone_Data/LAT_DP.html
