### ISSUE TITLE
Remove pre-launch files

### ISSUE THREAD

**Issue by donhorner** [fermi-lat/irfs#9]
It was pointed out that we have some files in caldb that fail fverify.  These files are pre-launch files used for the data challenge.  We did not distribute these files with the FSSC's ScienceTools releases.  It looks like they got added back in when we imported SLAC's CVS into github for the Fermitools.  We should compare with the old FSSC's caldb and remove any old files from github that were not in it.

**Comment by jasercion** [comment]
Todo: Clean up and consolidate caldb/caldb_release

**Comment by jasercion** [comment]
Competed with merge of P8R3_V3 branch
